services:
  postgres:
    image: postgres:16-alpine
    container_name: user_profile_pg
    environment:
      POSTGRES_DB: lucid
      POSTGRES_USER: lucid
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
